version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Montreal
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: copy-webpack-plugin
    versions:
    - ">= 6.0.a, < 6.1"
  - dependency-name: copy-webpack-plugin
    versions:
    - ">= 6.a, < 7"
  - dependency-name: postcss-flexbugs-fixes
    versions:
    - ">= 5.a, < 6"
  - dependency-name: postcss-loader
    versions:
    - ">= 4.a, < 5"
  - dependency-name: simple-keyboard
    versions:
    - 2.32.104
    - 2.32.105
    - 2.32.106
    - 2.32.107
    - 2.32.109
    - 2.32.129
    - 2.32.99
    - 3.0.2
    - 3.0.20
    - 3.0.34
    - 3.0.50
    - 3.0.51
    - 3.0.8
  - dependency-name: webpack
    versions:
    - 5.34.0
